package py.com.electoralvoteapp.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import py.com.electoralvoteapp.entities.Candidates;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CANDIDATES".
*/
public class CandidatesDao extends AbstractDao<Candidates, Long> {

    public static final String TABLENAME = "CANDIDATES";

    /**
     * Properties of entity Candidates.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CandidatesId = new Property(1, Integer.class, "candidatesId", false, "CANDIDATES_ID");
        public final static Property Active = new Property(2, Boolean.class, "active", false, "ACTIVE");
        public final static Property Description = new Property(3, String.class, "description", false, "DESCRIPTION");
        public final static Property Vote = new Property(4, Integer.class, "vote", false, "VOTE");
        public final static Property CreatedAt = new Property(5, String.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(6, String.class, "updatedAt", false, "UPDATED_AT");
    };


    public CandidatesDao(DaoConfig config) {
        super(config);
    }
    
    public CandidatesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CANDIDATES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CANDIDATES_ID\" INTEGER," + // 1: candidatesId
                "\"ACTIVE\" INTEGER," + // 2: active
                "\"DESCRIPTION\" TEXT," + // 3: description
                "\"VOTE\" INTEGER," + // 4: vote
                "\"CREATED_AT\" TEXT," + // 5: createdAt
                "\"UPDATED_AT\" TEXT);"); // 6: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CANDIDATES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Candidates entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer candidatesId = entity.getCandidatesId();
        if (candidatesId != null) {
            stmt.bindLong(2, candidatesId);
        }
 
        Boolean active = entity.getActive();
        if (active != null) {
            stmt.bindLong(3, active ? 1L: 0L);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
 
        Integer vote = entity.getVote();
        if (vote != null) {
            stmt.bindLong(5, vote);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(6, createdAt);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(7, updatedAt);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Candidates readEntity(Cursor cursor, int offset) {
        Candidates entity = new Candidates( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // candidatesId
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // active
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // vote
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // createdAt
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // updatedAt
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Candidates entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCandidatesId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setActive(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVote(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setCreatedAt(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUpdatedAt(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Candidates entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Candidates entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
