package py.com.electoralvoteapp.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CANDIDATES".
 */
public class Candidates {

    private Long id;
    private Integer candidatesId;
    private Boolean active;
    private String description;
    private Integer vote;
    private String createdAt;
    private String updatedAt;

    public Candidates() {
    }

    public Candidates(Long id) {
        this.id = id;
    }

    public Candidates(Long id, Integer candidatesId, Boolean active, String description, Integer vote, String createdAt, String updatedAt) {
        this.id = id;
        this.candidatesId = candidatesId;
        this.active = active;
        this.description = description;
        this.vote = vote;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCandidatesId() {
        return candidatesId;
    }

    public void setCandidatesId(Integer candidatesId) {
        this.candidatesId = candidatesId;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getVote() {
        return vote;
    }

    public void setVote(Integer vote) {
        this.vote = vote;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return "Candidates{" +
                "id=" + id +
                ", candidatesId=" + candidatesId +
                ", active=" + active +
                ", description='" + description + '\'' +
                ", vote=" + vote +
                ", createdAt='" + createdAt + '\'' +
                ", updatedAt='" + updatedAt + '\'' +
                '}';
    }
}
