package py.com.electoralvoteapp.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import py.com.electoralvoteapp.entities.Notifications;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTIFICATIONS".
*/
public class NotificationsDao extends AbstractDao<Notifications, Long> {

    public static final String TABLENAME = "NOTIFICATIONS";

    /**
     * Properties of entity Notifications.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property HttpDetail = new Property(2, String.class, "httpDetail", false, "HTTP_DETAIL");
        public final static Property Status = new Property(3, Integer.class, "status", false, "STATUS");
        public final static Property SendAppDate = new Property(4, String.class, "sendAppDate", false, "SEND_APP_DATE");
        public final static Property CreatedAt = new Property(5, Long.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(6, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
        public final static Property Observation = new Property(7, String.class, "observation", false, "OBSERVATION");
        public final static Property TabletNumber = new Property(8, String.class, "tabletNumber", false, "TABLET_NUMBER");
        public final static Property Queued = new Property(9, Integer.class, "queued", false, "QUEUED");
    };


    public NotificationsDao(DaoConfig config) {
        super(config);
    }
    
    public NotificationsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTIFICATIONS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TYPE\" TEXT," + // 1: type
                "\"HTTP_DETAIL\" TEXT," + // 2: httpDetail
                "\"STATUS\" INTEGER," + // 3: status
                "\"SEND_APP_DATE\" TEXT," + // 4: sendAppDate
                "\"CREATED_AT\" INTEGER," + // 5: createdAt
                "\"UPDATED_AT\" INTEGER," + // 6: updatedAt
                "\"OBSERVATION\" TEXT," + // 7: observation
                "\"TABLET_NUMBER\" TEXT," + // 8: tabletNumber
                "\"QUEUED\" INTEGER);"); // 9: queued
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTIFICATIONS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Notifications entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
 
        String httpDetail = entity.getHttpDetail();
        if (httpDetail != null) {
            stmt.bindString(3, httpDetail);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(4, status);
        }
 
        String sendAppDate = entity.getSendAppDate();
        if (sendAppDate != null) {
            stmt.bindString(5, sendAppDate);
        }
 
        Long createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(6, createdAt);
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(7, updatedAt.getTime());
        }
 
        String observation = entity.getObservation();
        if (observation != null) {
            stmt.bindString(8, observation);
        }
 
        String tabletNumber = entity.getTabletNumber();
        if (tabletNumber != null) {
            stmt.bindString(9, tabletNumber);
        }
 
        Integer queued = entity.getQueued();
        if (queued != null) {
            stmt.bindLong(10, queued);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Notifications readEntity(Cursor cursor, int offset) {
        Notifications entity = new Notifications( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // httpDetail
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // status
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // sendAppDate
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // createdAt
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // updatedAt
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // observation
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // tabletNumber
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9) // queued
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Notifications entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHttpDetail(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStatus(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setSendAppDate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreatedAt(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setUpdatedAt(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setObservation(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTabletNumber(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setQueued(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Notifications entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Notifications entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
