package py.com.electoralvoteapp.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTIFICATIONS".
 */
public class Notifications {

    private Long id;
    private String type;
    private String httpDetail;
    private Integer status;
    private String sendAppDate;
    private Long createdAt;
    private java.util.Date updatedAt;
    private String observation;
    private String tabletNumber;
    private Integer queued;

    public Notifications() {
    }

    public Notifications(Long id) {
        this.id = id;
    }

    public Notifications(Long id, String type, String httpDetail, Integer status, String sendAppDate, Long createdAt, java.util.Date updatedAt, String observation, String tabletNumber, Integer queued) {
        this.id = id;
        this.type = type;
        this.httpDetail = httpDetail;
        this.status = status;
        this.sendAppDate = sendAppDate;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.observation = observation;
        this.tabletNumber = tabletNumber;
        this.queued = queued;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getHttpDetail() {
        return httpDetail;
    }

    public void setHttpDetail(String httpDetail) {
        this.httpDetail = httpDetail;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getSendAppDate() {
        return sendAppDate;
    }

    public void setSendAppDate(String sendAppDate) {
        this.sendAppDate = sendAppDate;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getObservation() {
        return observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public String getTabletNumber() {
        return tabletNumber;
    }

    public void setTabletNumber(String tabletNumber) {
        this.tabletNumber = tabletNumber;
    }

    public Integer getQueued() {
        return queued;
    }

    public void setQueued(Integer queued) {
        this.queued = queued;
    }

}
