package py.com.electoralvoteapp.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import py.com.electoralvoteapp.entities.TableVotes;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TABLE_VOTES".
*/
public class TableVotesDao extends AbstractDao<TableVotes, Long> {

    public static final String TABLENAME = "TABLE_VOTES";

    /**
     * Properties of entity TableVotes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TableVotesId = new Property(1, Integer.class, "tableVotesId", false, "TABLE_VOTES_ID");
        public final static Property Complete = new Property(2, Boolean.class, "complete", false, "COMPLETE");
        public final static Property Description = new Property(3, String.class, "description", false, "DESCRIPTION");
        public final static Property NumberTable = new Property(4, Integer.class, "numberTable", false, "NUMBER_TABLE");
    };


    public TableVotesDao(DaoConfig config) {
        super(config);
    }
    
    public TableVotesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TABLE_VOTES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TABLE_VOTES_ID\" INTEGER," + // 1: tableVotesId
                "\"COMPLETE\" INTEGER," + // 2: complete
                "\"DESCRIPTION\" TEXT," + // 3: description
                "\"NUMBER_TABLE\" INTEGER);"); // 4: numberTable
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TABLE_VOTES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TableVotes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer tableVotesId = entity.getTableVotesId();
        if (tableVotesId != null) {
            stmt.bindLong(2, tableVotesId);
        }
 
        Boolean complete = entity.getComplete();
        if (complete != null) {
            stmt.bindLong(3, complete ? 1L: 0L);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
 
        Integer numberTable = entity.getNumberTable();
        if (numberTable != null) {
            stmt.bindLong(5, numberTable);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TableVotes readEntity(Cursor cursor, int offset) {
        TableVotes entity = new TableVotes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // tableVotesId
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // complete
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4) // numberTable
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TableVotes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTableVotesId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setComplete(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNumberTable(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TableVotes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TableVotes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
