package py.com.electoralvoteapp.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TABLE_VOTES".
 */
public class TableVotes {

    private Long id;
    private Integer tableVotesId;
    private Boolean complete;
    private String description;
    private Integer numberTable;

    public TableVotes() {
    }

    public TableVotes(Long id) {
        this.id = id;
    }

    public TableVotes(Long id, Integer tableVotesId, Boolean complete, String description, Integer numberTable) {
        this.id = id;
        this.tableVotesId = tableVotesId;
        this.complete = complete;
        this.description = description;
        this.numberTable = numberTable;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTableVotesId() {
        return tableVotesId;
    }

    public void setTableVotesId(Integer tableVotesId) {
        this.tableVotesId = tableVotesId;
    }

    public Boolean getComplete() {
        return complete;
    }

    public void setComplete(Boolean complete) {
        this.complete = complete;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getNumberTable() {
        return numberTable;
    }

    public void setNumberTable(Integer numberTable) {
        this.numberTable = numberTable;
    }

}
